// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDUafadY7LH5Cp0QwJE8RffoOOzDf-4dpg',
    appId: '1:77157915215:web:325187d4e0fd7ec4a2683a',
    messagingSenderId: '77157915215',
    projectId: 'devhub-c22ff',
    authDomain: 'devhub-c22ff.firebaseapp.com',
    storageBucket: 'devhub-c22ff.appspot.com',
    measurementId: 'G-FXFG03SN9D',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDhvmJcWFr1GIUDa86327SRYoIJZH0t1nw',
    appId: '1:77157915215:android:4ef8ebbdb6022a22a2683a',
    messagingSenderId: '77157915215',
    projectId: 'devhub-c22ff',
    storageBucket: 'devhub-c22ff.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCn_foX87-WCIC5sCtWWCodm0NjKEq-u7I',
    appId: '1:77157915215:ios:062e1fec592beefba2683a',
    messagingSenderId: '77157915215',
    projectId: 'devhub-c22ff',
    storageBucket: 'devhub-c22ff.appspot.com',
    iosBundleId: 'com.devhub.devhub',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCn_foX87-WCIC5sCtWWCodm0NjKEq-u7I',
    appId: '1:77157915215:ios:518016c94b899fb7a2683a',
    messagingSenderId: '77157915215',
    projectId: 'devhub-c22ff',
    storageBucket: 'devhub-c22ff.appspot.com',
    iosBundleId: 'com.devhub.devhub.RunnerTests',
  );
}
